--------------------------------------------------------
-- Archivo creado  - jueves-septiembre-03-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARCHIVOS
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."ARCHIVOS" 
   (	"ARCHIVO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ARCHIVO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BANCO
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."BANCO" 
   (	"RFC" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BITACORA
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."BITACORA" 
   (	"ID_BITACORA" NUMBER(*,0), 
	"ID_ACCION" NUMBER(*,0), 
	"NO_CUENTA" VARCHAR2(40 BYTE), 
	"DETALLE_ACCION" VARCHAR2(200 BYTE), 
	"FECHA" DATE, 
	"ID_ERROR" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARGOS_NO_RECONOCIDOS
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."CARGOS_NO_RECONOCIDOS" 
   (	"ID_TRANSACCION" VARCHAR2(40 BYTE), 
	"ID_ESTADO_CUENTA" VARCHAR2(30 BYTE), 
	"DETALLE" VARCHAR2(200 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATALOGO_ACCION
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."CATALOGO_ACCION" 
   (	"ID_ACCION" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CODIGO_ERRORES
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."CODIGO_ERRORES" 
   (	"ID_ERROR" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADO_CUENTA
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."ESTADO_CUENTA" 
   (	"ID_ESTADO_CUENTA" VARCHAR2(30 BYTE), 
	"NO_CUENTA" VARCHAR2(40 BYTE), 
	"FECHA_CORTE" DATE, 
	"ECD" BLOB, 
	"NOMENCLATURA_HTML" VARCHAR2(50 BYTE), 
	"PDF" BLOB, 
	"NOMENCLATURA_PDF" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ECD") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PDF") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MESES_SIN_INTERESES
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."MESES_SIN_INTERESES" 
   (	"ID_TRANSACCION" VARCHAR2(40 BYTE), 
	"ID_ESTADO_CUENTA" VARCHAR2(30 BYTE), 
	"PLANMSI" VARCHAR2(30 BYTE), 
	"DETALLE" VARCHAR2(200 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAPERLESS
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."PAPERLESS" 
   (	"ID_PAPERLESS" NUMBER(*,0), 
	"NO_CUENTA" VARCHAR2(40 BYTE), 
	"APLICA" CHAR(1 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TARJETA_HABIENTE
--------------------------------------------------------

  CREATE TABLE "TSYS_EDC_01"."TARJETA_HABIENTE" 
   (	"NO_CUENTA" VARCHAR2(40 BYTE), 
	"RFC_BANCO" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"AP_PATERNO" VARCHAR2(30 BYTE), 
	"AP_MATERNO" VARCHAR2(30 BYTE), 
	"DIR_CALLE" VARCHAR2(100 BYTE), 
	"DIR_COLONIA" VARCHAR2(100 BYTE), 
	"DIR_CIUDAD" VARCHAR2(60 BYTE), 
	"DIR_ESTADO" VARCHAR2(60 BYTE), 
	"DIR_CP" VARCHAR2(5 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TSYS_EDC_01.BANCO
SET DEFINE OFF;
Insert into TSYS_EDC_01.BANCO (RFC,NOMBRE,RAZON_SOCIAL) values ('BNMX150912BN0','BANAMEX','BANCO');
REM INSERTING into TSYS_EDC_01.BITACORA
SET DEFINE OFF;
REM INSERTING into TSYS_EDC_01.CARGOS_NO_RECONOCIDOS
SET DEFINE OFF;
REM INSERTING into TSYS_EDC_01.CATALOGO_ACCION
SET DEFINE OFF;
REM INSERTING into TSYS_EDC_01.CODIGO_ERRORES
SET DEFINE OFF;
REM INSERTING into TSYS_EDC_01.ESTADO_CUENTA
SET DEFINE OFF;
Insert into TSYS_EDC_01.ESTADO_CUENTA (ID_ESTADO_CUENTA,NO_CUENTA,FECHA_CORTE,NOMENCLATURA_HTML,NOMENCLATURA_PDF) values ('000XXXXXXXXXXXXXX3025022015','000XXXXXXXXXXXXXX30',to_date('25/02/15','DD/MM/RR'),'000XXXXXXXXXXXXXX3025022015.html','000XXXXXXXXXXXXXX3025022015.pdf');
Insert into TSYS_EDC_01.ESTADO_CUENTA (ID_ESTADO_CUENTA,NO_CUENTA,FECHA_CORTE,NOMENCLATURA_HTML,NOMENCLATURA_PDF) values ('000XXXXXXXXXXXXXX4025022015','000XXXXXXXXXXXXXX40',to_date('25/02/15','DD/MM/RR'),'000XXXXXXXXXXXXXX4025022015.html','000XXXXXXXXXXXXXX4025022015.pdf');
Insert into TSYS_EDC_01.ESTADO_CUENTA (ID_ESTADO_CUENTA,NO_CUENTA,FECHA_CORTE,NOMENCLATURA_HTML,NOMENCLATURA_PDF) values ('000XXXXXXXXXXXXXX5025022015','000XXXXXXXXXXXXXX50',to_date('25/02/15','DD/MM/RR'),'000XXXXXXXXXXXXXX5025022015.html','000XXXXXXXXXXXXXX5025022015.pdf');
Insert into TSYS_EDC_01.ESTADO_CUENTA (ID_ESTADO_CUENTA,NO_CUENTA,FECHA_CORTE,NOMENCLATURA_HTML,NOMENCLATURA_PDF) values ('000XXXXXXXXXXXXXX1025022015','000XXXXXXXXXXXXXX10',to_date('25/02/15','DD/MM/RR'),'000XXXXXXXXXXXXXX1025022015.html','000XXXXXXXXXXXXXX1025022015.pdf');
Insert into TSYS_EDC_01.ESTADO_CUENTA (ID_ESTADO_CUENTA,NO_CUENTA,FECHA_CORTE,NOMENCLATURA_HTML,NOMENCLATURA_PDF) values ('000XXXXXXXXXXXXXX2025022015','000XXXXXXXXXXXXXX20',to_date('25/02/15','DD/MM/RR'),'000XXXXXXXXXXXXXX2025022015.html','000XXXXXXXXXXXXXX2025022015.pdf');
REM INSERTING into TSYS_EDC_01.MESES_SIN_INTERESES
SET DEFINE OFF;
REM INSERTING into TSYS_EDC_01.PAPERLESS
SET DEFINE OFF;
REM INSERTING into TSYS_EDC_01.TARJETA_HABIENTE
SET DEFINE OFF;
Insert into TSYS_EDC_01.TARJETA_HABIENTE (NO_CUENTA,RFC_BANCO,NOMBRE,AP_PATERNO,AP_MATERNO,DIR_CALLE,DIR_COLONIA,DIR_CIUDAD,DIR_ESTADO,DIR_CP,PASSWORD) values ('000XXXXXXXXXXXXXX20','BNMX150912BN0','2XXXXXXXXX','XXXXX','XXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',null,null,'01720','Pass');
Insert into TSYS_EDC_01.TARJETA_HABIENTE (NO_CUENTA,RFC_BANCO,NOMBRE,AP_PATERNO,AP_MATERNO,DIR_CALLE,DIR_COLONIA,DIR_CIUDAD,DIR_ESTADO,DIR_CP,PASSWORD) values ('000XXXXXXXXXXXXXX30','BNMX150912BN0','3XXX','XXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',null,null,'03100','Pass');
Insert into TSYS_EDC_01.TARJETA_HABIENTE (NO_CUENTA,RFC_BANCO,NOMBRE,AP_PATERNO,AP_MATERNO,DIR_CALLE,DIR_COLONIA,DIR_CIUDAD,DIR_ESTADO,DIR_CP,PASSWORD) values ('000XXXXXXXXXXXXXX40','BNMX150912BN0','4XXXX','XXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',null,null,'01900','Pass');
Insert into TSYS_EDC_01.TARJETA_HABIENTE (NO_CUENTA,RFC_BANCO,NOMBRE,AP_PATERNO,AP_MATERNO,DIR_CALLE,DIR_COLONIA,DIR_CIUDAD,DIR_ESTADO,DIR_CP,PASSWORD) values ('000XXXXXXXXXXXXXX50','BNMX150912BN0','5XXX','XXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',null,null,'39890','Pass');
Insert into TSYS_EDC_01.TARJETA_HABIENTE (NO_CUENTA,RFC_BANCO,NOMBRE,AP_PATERNO,AP_MATERNO,DIR_CALLE,DIR_COLONIA,DIR_CIUDAD,DIR_ESTADO,DIR_CP,PASSWORD) values ('000XXXXXXXXXXXXXX10','BNMX150912BN0','1XXXXXXX','XXXXXXXX','XXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',null,null,'64790','Pass');
--------------------------------------------------------
--  DDL for Index SYS_C007087
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007087" ON "TSYS_EDC_01"."BANCO" ("RFC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007109
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007109" ON "TSYS_EDC_01"."BITACORA" ("ID_BITACORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007101
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007101" ON "TSYS_EDC_01"."CARGOS_NO_RECONOCIDOS" ("ID_TRANSACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007107
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007107" ON "TSYS_EDC_01"."CATALOGO_ACCION" ("ID_ACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007113
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007113" ON "TSYS_EDC_01"."CODIGO_ERRORES" ("ID_ERROR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007092
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007092" ON "TSYS_EDC_01"."ESTADO_CUENTA" ("ID_ESTADO_CUENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007098
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007098" ON "TSYS_EDC_01"."MESES_SIN_INTERESES" ("ID_TRANSACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007104
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007104" ON "TSYS_EDC_01"."PAPERLESS" ("ID_PAPERLESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007089
--------------------------------------------------------

  CREATE UNIQUE INDEX "TSYS_EDC_01"."SYS_C007089" ON "TSYS_EDC_01"."TARJETA_HABIENTE" ("NO_CUENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BANCO
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."BANCO" ADD PRIMARY KEY ("RFC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."BANCO" MODIFY ("RFC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BITACORA
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."BITACORA" ADD PRIMARY KEY ("ID_BITACORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."BITACORA" MODIFY ("ID_BITACORA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARGOS_NO_RECONOCIDOS
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."CARGOS_NO_RECONOCIDOS" ADD PRIMARY KEY ("ID_TRANSACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."CARGOS_NO_RECONOCIDOS" MODIFY ("ID_TRANSACCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATALOGO_ACCION
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."CATALOGO_ACCION" ADD PRIMARY KEY ("ID_ACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."CATALOGO_ACCION" MODIFY ("ID_ACCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CODIGO_ERRORES
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."CODIGO_ERRORES" ADD PRIMARY KEY ("ID_ERROR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."CODIGO_ERRORES" MODIFY ("ID_ERROR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO_CUENTA
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."ESTADO_CUENTA" ADD PRIMARY KEY ("ID_ESTADO_CUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."ESTADO_CUENTA" MODIFY ("ID_ESTADO_CUENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MESES_SIN_INTERESES
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."MESES_SIN_INTERESES" ADD PRIMARY KEY ("ID_TRANSACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."MESES_SIN_INTERESES" MODIFY ("ID_TRANSACCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAPERLESS
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."PAPERLESS" ADD PRIMARY KEY ("ID_PAPERLESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."PAPERLESS" MODIFY ("ID_PAPERLESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TARJETA_HABIENTE
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."TARJETA_HABIENTE" ADD PRIMARY KEY ("NO_CUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TSYS_EDC_01"."TARJETA_HABIENTE" MODIFY ("NO_CUENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BITACORA
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."BITACORA" ADD FOREIGN KEY ("ID_ACCION")
	  REFERENCES "TSYS_EDC_01"."CATALOGO_ACCION" ("ID_ACCION") ENABLE;
  ALTER TABLE "TSYS_EDC_01"."BITACORA" ADD FOREIGN KEY ("NO_CUENTA")
	  REFERENCES "TSYS_EDC_01"."TARJETA_HABIENTE" ("NO_CUENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARGOS_NO_RECONOCIDOS
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."CARGOS_NO_RECONOCIDOS" ADD FOREIGN KEY ("ID_ESTADO_CUENTA")
	  REFERENCES "TSYS_EDC_01"."ESTADO_CUENTA" ("ID_ESTADO_CUENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADO_CUENTA
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."ESTADO_CUENTA" ADD FOREIGN KEY ("NO_CUENTA")
	  REFERENCES "TSYS_EDC_01"."TARJETA_HABIENTE" ("NO_CUENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESES_SIN_INTERESES
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."MESES_SIN_INTERESES" ADD FOREIGN KEY ("ID_ESTADO_CUENTA")
	  REFERENCES "TSYS_EDC_01"."ESTADO_CUENTA" ("ID_ESTADO_CUENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAPERLESS
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."PAPERLESS" ADD FOREIGN KEY ("NO_CUENTA")
	  REFERENCES "TSYS_EDC_01"."TARJETA_HABIENTE" ("NO_CUENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TARJETA_HABIENTE
--------------------------------------------------------

  ALTER TABLE "TSYS_EDC_01"."TARJETA_HABIENTE" ADD FOREIGN KEY ("RFC_BANCO")
	  REFERENCES "TSYS_EDC_01"."BANCO" ("RFC") ENABLE;
